let btn1 = document.querySelector(".btn1");
let btn2 = document.querySelector(".btn2");
let btn3 = document.querySelector(".btn3");
let btn4 = document.querySelector(".btn4");
let btn5 = document.querySelector(".btn5");
let btn6 = document.querySelector(".btn6");
let btn7 = document.querySelector(".btn7");
let btn8 = document.querySelector(".btn8");
let btn9 = document.querySelector(".btn9");
let blk1 = document.querySelector(".blk1");
let blk2 = document.querySelector(".blk2");
let blk3 = document.querySelector(".blk3");
let blk4 = document.querySelector(".blk4");
let blk5 = document.querySelector(".blk5");
let blk6 = document.querySelector(".blk6");
let blk7 = document.querySelector(".blk7");
let blk8 = document.querySelector(".blk8");
let blk9 = document.querySelector(".blk9");

btn1.addEventListener("click", function(){
    btn1.classList.add("active");
    btn2.classList.remove("active");
    btn3.classList.remove("active");
    btn4.classList.remove("active");
    btn5.classList.remove("active");
    btn6.classList.remove("active");
    btn7.classList.remove("active");
    btn8.classList.remove("active");
    btn9.classList.remove("active");    
    blk1.style.display = 'block';
    blk2.style.display = 'none';
    blk3.style.display = 'none';
    blk4.style.display = 'none';
    blk5.style.display = 'none';
    blk6.style.display = 'none';
    blk7.style.display = 'none';
    blk8.style.display = 'none';
    blk9.style.display = 'none';
});

btn2.addEventListener("click", function(){
    btn1.classList.remove("active");
    btn2.classList.add("active");
    btn3.classList.remove("active"); 
    btn4.classList.remove("active");
    btn5.classList.remove("active");
    btn6.classList.remove("active");
    btn7.classList.remove("active");
    btn8.classList.remove("active");
    btn9.classList.remove("active");  
    blk1.style.display = 'none';
    blk2.style.display = 'block';
    blk3.style.display = 'none';
    blk4.style.display = 'none';
    blk5.style.display = 'none';
    blk6.style.display = 'none';
    blk7.style.display = 'none';
    blk8.style.display = 'none';
    blk9.style.display = 'none';
});

btn3.addEventListener("click", function(){
    btn1.classList.remove("active");
    btn2.classList.remove("active");
    btn3.classList.add("active"); 
    btn4.classList.remove("active");
    btn5.classList.remove("active");
    btn6.classList.remove("active");
    btn7.classList.remove("active");
    btn8.classList.remove("active");
    btn9.classList.remove("active");  
    blk1.style.display = 'none';
    blk2.style.display = 'none';
    blk4.style.display = 'none';
    blk3.style.display = 'block';
    blk5.style.display = 'none';
    blk6.style.display = 'none';
    blk7.style.display = 'none';
    blk8.style.display = 'none';
    blk9.style.display = 'none';
});

btn4.addEventListener("click", function(){
    btn1.classList.remove("active");
    btn2.classList.remove("active");
    btn3.classList.remove("active"); 
    btn4.classList.add("active");
    btn5.classList.remove("active");
    btn6.classList.remove("active");
    btn7.classList.remove("active");
    btn8.classList.remove("active");
    btn9.classList.remove("active");  
    blk1.style.display = 'none';
    blk2.style.display = 'none';
    blk3.style.display = 'none';
    blk4.style.display = 'block';
    blk5.style.display = 'none';
    blk6.style.display = 'none';
    blk7.style.display = 'none';
    blk8.style.display = 'none';
    blk9.style.display = 'none';
});

btn5.addEventListener("click", function(){
    btn1.classList.remove("active");
    btn2.classList.remove("active");
    btn3.classList.remove("active"); 
    btn4.classList.remove("active");
    btn5.classList.add("active");
    btn6.classList.remove("active");
    btn7.classList.remove("active");
    btn8.classList.remove("active");
    btn9.classList.remove("active");  
    blk1.style.display = 'none';
    blk2.style.display = 'none';
    blk3.style.display = 'none';
    blk4.style.display = 'none';
    blk5.style.display = 'block';
    blk6.style.display = 'none';
    blk7.style.display = 'none';
    blk8.style.display = 'none';
    blk9.style.display = 'none';
});

btn6.addEventListener("click", function(){
    btn1.classList.remove("active");
    btn2.classList.remove("active");
    btn3.classList.remove("active"); 
    btn4.classList.remove("active");
    btn5.classList.remove("active");
    btn6.classList.add("active");
    btn7.classList.remove("active");
    btn8.classList.remove("active");
    btn9.classList.remove("active");  
    blk1.style.display = 'none';
    blk2.style.display = 'none';
    blk3.style.display = 'none';
    blk4.style.display = 'none';
    blk5.style.display = 'none';
    blk6.style.display = 'block';
    blk7.style.display = 'none';
    blk8.style.display = 'none';
    blk9.style.display = 'none';
});

btn7.addEventListener("click", function(){
    btn1.classList.remove("active");
    btn2.classList.remove("active");
    btn3.classList.remove("active"); 
    btn4.classList.remove("active");
    btn5.classList.remove("active");
    btn6.classList.remove("active");
    btn7.classList.add("active");
    btn8.classList.remove("active");
    btn9.classList.remove("active");  
    blk1.style.display = 'none';
    blk2.style.display = 'none';
    blk3.style.display = 'none';
    blk4.style.display = 'none';
    blk5.style.display = 'none';
    blk6.style.display = 'none';
    blk7.style.display = 'block';
    blk8.style.display = 'none';
    blk9.style.display = 'none';
});

btn8.addEventListener("click", function(){
    btn1.classList.remove("active");
    btn2.classList.remove("active");
    btn3.classList.remove("active"); 
    btn4.classList.remove("active");
    btn5.classList.remove("active");
    btn6.classList.remove("active");
    btn7.classList.remove("active");
    btn8.classList.add("active");
    btn9.classList.remove("active");  
    blk1.style.display = 'none';
    blk2.style.display = 'none';
    blk3.style.display = 'none';
    blk4.style.display = 'none';
    blk5.style.display = 'none';
    blk6.style.display = 'none';
    blk7.style.display = 'none';
    blk8.style.display = 'block';
    blk9.style.display = 'none';
});

btn9.addEventListener("click", function(){
    btn1.classList.remove("active");
    btn2.classList.remove("active");
    btn3.classList.remove("active"); 
    btn4.classList.remove("active");
    btn5.classList.remove("active");
    btn6.classList.remove("active");
    btn7.classList.remove("active");
    btn8.classList.remove("active");
    btn9.classList.add("active");  
    blk1.style.display = 'none';
    blk2.style.display = 'none';
    blk3.style.display = 'none';
    blk4.style.display = 'none';
    blk5.style.display = 'none';
    blk6.style.display = 'none';
    blk7.style.display = 'none';
    blk8.style.display = 'none';
    blk9.style.display = 'block';
});